/**
 * Authentic Operational Mock Data Grounded in Backend Entities
 * Represents real scenarios tested across Phases 5-13.
 */

import { FullIncidentContext, Incident, Evidence, ActionPlan, PolicyEvaluationResult, ExecutionResult, Outcome } from '../types/domain';

export const MOCK_MERCHANT = {
  merchant_id: 'merch_acme_tech_01',
  name: 'Acme Digital Commerce Pvt Ltd',
  currency: 'INR',
  timezone: 'Asia/Kolkata',
  status: 'active',
  environment: 'Razorpay Test Mode',
};

export const MOCK_INCIDENTS_CONTEXT: Record<string, FullIncidentContext> = {
  'inc_hdfc_drop_01': {
    incident: {
      incident_id: 'inc_hdfc_drop_01',
      merchant_id: 'merch_acme_tech_01',
      incident_type: 'payment_drop_spike',
      severity: 'high',
      status: 'resolved',
      detected_at: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
      revenue_at_risk: '45000.00',
      currency: 'INR',
      confidence: '0.92',
      description: 'Severe 84% conversion drop detected on HDFC Netbanking checkout route.',
    },
    evidences: [
      {
        evidence_id: 'ev_hdfc_01',
        incident_id: 'inc_hdfc_drop_01',
        evidence_type: 'telemetry_metric',
        source: 'gateway_telemetry_stream',
        observed_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        summary: 'HDFC Netbanking route timeout rate escalated to 14.8% (baseline: 0.12%).',
        metrics_data: { error_rate: 0.148, baseline_rate: 0.0012, affected_gateway: 'HDFC_DIRECT' },
      },
      {
        evidence_id: 'ev_hdfc_02',
        incident_id: 'inc_hdfc_drop_01',
        evidence_type: 'api_trace',
        source: 'razorpay_gateway_logs',
        observed_at: new Date(Date.now() - 38 * 60 * 1000).toISOString(),
        summary: 'Upstream gateway socket timeout during bank OTP redirection handshake.',
        metrics_data: { http_status: 504, p99_latency_ms: 4850, bank_code: 'HDFC' },
      },
      {
        evidence_id: 'ev_hdfc_03',
        incident_id: 'inc_hdfc_drop_01',
        evidence_type: 'statistical_anomaly',
        source: 'conversion_funnel_monitor',
        observed_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
        summary: 'Completed checkout funnel dropped from 78.4% to 12.1% specifically on mobile web.',
        metrics_data: { cohort: 'HDFC_NETBANKING_MOBILE', funnel_drop_pct: 84.5 },
      },
    ],
    investigation: {
      incident_id: 'inc_hdfc_drop_01',
      primary_cause: 'HDFC Netbanking authentication gateway unresponsive with recurrent HTTP 504 timeouts.',
      secondary_causes: ['Mobile checkout retry amplification causing queue backlog.'],
      confidence: 0.94,
      confidence_rationale: 'Telemetry stream exhibits sharp 14.8% error rate tightly localized to HDFC direct bank route while secondary rails remain healthy.',
      affected_cohorts: ['HDFC_NETBANKING', 'MOBILE_CHECKOUT_HDFC'],
      evidence_keys_used: ['ev_hdfc_01', 'ev_hdfc_02', 'ev_hdfc_03'],
      is_conclusive: true,
    },
    proposed_action: {
      action_id: 'act_reroute_01',
      incident_id: 'inc_hdfc_drop_01',
      action_type: 'gateway_reroute',
      target: 'gateway_axis_secondary_netbanking',
      expected_recovery: '35000.00',
      currency: 'INR',
      risk_level: 'low',
      confidence: '0.88',
      approval_required: false,
      status: 'completed',
      rationale: 'Dynamically reroute HDFC netbanking traffic to Axis Bank secondary aggregation rail to bypass degraded direct link.',
      created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    policy_decision: {
      decision_id: 'pol_dec_01',
      action_id: 'act_reroute_01',
      incident_id: 'inc_hdfc_drop_01',
      merchant_id: 'merch_acme_tech_01',
      decision: 'allow',
      reasons: [
        'Expected recovery ₹35,000.00 is within auto-allow threshold of ₹50,000.00.',
        'Low operational risk intervention with verified routing capability.',
        'Confidence score 0.88 exceeds 0.70 auto-allow threshold.',
        'All input integrity and tenant isolation rules verified.',
      ],
      rule_results: [
        { rule_code: 'input_integrity', passed: true, decision_impact: 'allow', message: 'Tenant match and currency verified.', evaluated_data: {} },
        { rule_code: 'action_allowlist', passed: true, decision_impact: 'allow', message: 'gateway_reroute is on allowlist.', evaluated_data: {} },
        { rule_code: 'monetary_limit', passed: true, decision_impact: 'allow', message: 'Amount within ₹50,000 limit.', evaluated_data: { expected_recovery: '35000.00', limit: '50000.00' } },
        { rule_code: 'risk_threshold', passed: true, decision_impact: 'allow', message: 'Low risk intervention allowed.', evaluated_data: { risk_level: 'low' } },
        { rule_code: 'confidence_threshold', passed: true, decision_impact: 'allow', message: 'Confidence 0.88 meets auto-allow criteria.', evaluated_data: { confidence: '0.88' } },
        { rule_code: 'duplicate_protection', passed: true, decision_impact: 'allow', message: 'No conflicting active routing plans.', evaluated_data: {} },
      ],
      evaluated_limits: {
        max_auto_allow_recovery: '50000.00',
        max_absolute_recovery_cap: '500000.00',
        min_confidence_auto_allow: '0.70',
        policy_version: '1.0.0',
      },
      policy_version: '1.0.0',
      evaluated_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    },
    execution_result: {
      execution_id: 'exec_sim_01',
      merchant_id: 'merch_acme_tech_01',
      incident_id: 'inc_hdfc_drop_01',
      action_id: 'act_reroute_01',
      provider: 'simulation_adapter',
      action_type: 'gateway_reroute',
      status: 'simulated',
      is_simulated: true,
      provider_reference: 'sim_reroute_98a72b1',
      idempotency_key: 'exec_act_reroute_01_1725540000',
      executed_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      details: {
        simulated_operation: 'gateway_reroute',
        target_rail: 'gateway_axis_secondary_netbanking',
        mode: 'sandbox_simulation',
        notice: 'Executed truthfully under sandbox simulation adapter.',
      },
    },
    outcome: {
      outcome_id: 'out_hdfc_01',
      incident_id: 'inc_hdfc_drop_01',
      action_id: 'act_reroute_01',
      outcome_type: 'revenue_protected',
      amount: '35000.00',
      currency: 'INR',
      status: 'verified',
      measured_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      reference_data: {
        merchant_id: 'merch_acme_tech_01',
        incident_id: 'inc_hdfc_drop_01',
        action_id: 'act_reroute_01',
        execution_id: 'exec_sim_01',
        execution_status: 'simulated',
        execution_provider: 'simulation_adapter',
        is_simulated: true,
        verification_status: 'verified_success',
        revenue_at_risk: '45000.00',
        recovered_revenue: '0.00',
        protected_revenue: '35000.00',
        total_impact: '35000.00',
        recovery_rate: '0.7778',
        remaining_revenue_at_risk: '10000.00',
        correlation_id: 'corr-hdfc-01',
        evidence_ids: ['ev_hdfc_01', 'ev_hdfc_02', 'ev_hdfc_03'],
      },
    },
  },

  'inc_auth_surge_02': {
    incident: {
      incident_id: 'inc_auth_surge_02',
      merchant_id: 'merch_acme_tech_01',
      incident_type: 'authorization_failure_surge',
      severity: 'critical',
      status: 'action_proposed',
      detected_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      revenue_at_risk: '125000.00',
      currency: 'INR',
      confidence: '0.89',
      description: 'Surge in card authorization rejects on international Visa/Mastercard transactions.',
    },
    evidences: [
      {
        evidence_id: 'ev_auth_01',
        incident_id: 'inc_auth_surge_02',
        evidence_type: 'telemetry_metric',
        source: 'card_network_stream',
        observed_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
        summary: '3DS authentication challenges failing with bank acquirer connection drop.',
        metrics_data: { failure_rate: 0.32, impacted_volume: '125000.00' },
      },
      {
        evidence_id: 'ev_auth_02',
        incident_id: 'inc_auth_surge_02',
        evidence_type: 'log_excerpt',
        source: 'auth_service_logs',
        observed_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
        summary: 'Acquirer returned error 91: Issuer system down or unavailable.',
        metrics_data: { error_code: '91', network: 'VISA' },
      },
    ],
    investigation: {
      incident_id: 'inc_auth_surge_02',
      primary_cause: 'Primary acquirer 3DS server timeout affecting high-value international card authorizations.',
      secondary_causes: ['Fallback routing not triggered automatically due to missing 3DS2 flag.'],
      confidence: 0.89,
      confidence_rationale: 'Distinct error pattern 91 observed exclusively on primary card acquirer pipe.',
      affected_cohorts: ['INTERNATIONAL_CARDS', 'VISA_3DS'],
      evidence_keys_used: ['ev_auth_01', 'ev_auth_02'],
      is_conclusive: true,
    },
    proposed_action: {
      action_id: 'act_retry_02',
      incident_id: 'inc_auth_surge_02',
      action_type: 'retry_payment',
      target: 'razorpay_smart_retry_pool',
      expected_recovery: '85000.00',
      currency: 'INR',
      risk_level: 'medium',
      confidence: '0.85',
      approval_required: true,
      status: 'policy_check_pending',
      rationale: 'Re-dispatch failed authorizations through secondary acquiring network with 3DS1 fallback.',
      created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    policy_decision: {
      decision_id: 'pol_dec_02',
      action_id: 'act_retry_02',
      incident_id: 'inc_auth_surge_02',
      merchant_id: 'merch_acme_tech_01',
      decision: 'require_approval',
      reasons: [
        'Expected recovery ₹85,000.00 exceeds auto-allow threshold (₹50,000.00); requires explicit merchant authorization.',
        'Medium risk financial intervention requires human approval operator signoff.',
      ],
      rule_results: [
        { rule_code: 'input_integrity', passed: true, decision_impact: 'allow', message: 'Valid input format and currency match.', evaluated_data: {} },
        { rule_code: 'action_allowlist', passed: true, decision_impact: 'allow', message: 'retry_payment is permitted.', evaluated_data: {} },
        { rule_code: 'monetary_limit', passed: true, decision_impact: 'require_approval', message: 'Expected recovery ₹85,000.00 > ₹50,000.00 limit.', evaluated_data: { amount: '85000.00', auto_cap: '50000.00' } },
        { rule_code: 'risk_threshold', passed: true, decision_impact: 'require_approval', message: 'Medium risk recovery exceeding ₹25,000 requires human check.', evaluated_data: { risk: 'medium' } },
      ],
      evaluated_limits: {
        max_auto_allow_recovery: '50000.00',
        max_absolute_recovery_cap: '500000.00',
        policy_version: '1.0.0',
      },
      policy_version: '1.0.0',
      evaluated_at: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    },
  },

  'inc_webhook_lag_03': {
    incident: {
      incident_id: 'inc_webhook_lag_03',
      merchant_id: 'merch_acme_tech_01',
      incident_type: 'webhook_latency_spike',
      severity: 'medium',
      status: 'action_approved',
      detected_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      revenue_at_risk: '18000.00',
      currency: 'INR',
      confidence: '0.91',
      description: 'Payment confirmation webhooks delayed by >12 seconds, causing customer drop-off on fulfillment.',
    },
    evidences: [
      {
        evidence_id: 'ev_wh_01',
        incident_id: 'inc_webhook_lag_03',
        evidence_type: 'telemetry_metric',
        source: 'webhook_delivery_monitor',
        observed_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
        summary: 'P95 webhook delivery latency reached 14,200ms (target: <500ms).',
        metrics_data: { p95_latency_ms: 14200, backlog_count: 340 },
      },
    ],
    investigation: {
      incident_id: 'inc_webhook_lag_03',
      primary_cause: 'Webhook dispatch worker pool saturated due to slow acknowledgment on legacy merchant endpoint.',
      secondary_causes: [],
      confidence: 0.91,
      confidence_rationale: 'Queue depth increased concurrently with endpoint HTTP 429 backoff.',
      affected_cohorts: ['ASYNC_PAYMENT_NOTIFICATIONS'],
      evidence_keys_used: ['ev_wh_01'],
      is_conclusive: true,
    },
    proposed_action: {
      action_id: 'act_wh_03',
      incident_id: 'inc_webhook_lag_03',
      action_type: 'webhook_resync',
      target: 'webhook_delivery_fast_pipe',
      expected_recovery: '18000.00',
      currency: 'INR',
      risk_level: 'low',
      confidence: '0.90',
      approval_required: false,
      status: 'executing',
      rationale: 'Drain stuck queue into prioritized dedicated delivery pipeline and trigger bulk reconciliation replay.',
      created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    },
    policy_decision: {
      decision_id: 'pol_dec_03',
      action_id: 'act_wh_03',
      incident_id: 'inc_webhook_lag_03',
      merchant_id: 'merch_acme_tech_01',
      decision: 'allow',
      reasons: ['Amount ₹18,000.00 is within auto-allow threshold.', 'Low operational risk.'],
      rule_results: [
        { rule_code: 'input_integrity', passed: true, decision_impact: 'allow', message: 'Passed.', evaluated_data: {} },
        { rule_code: 'monetary_limit', passed: true, decision_impact: 'allow', message: 'Within auto-allow cap.', evaluated_data: {} },
      ],
      evaluated_limits: { policy_version: '1.0.0' },
      policy_version: '1.0.0',
      evaluated_at: new Date(Date.now() - 17 * 60 * 1000).toISOString(),
    },
    execution_result: {
      execution_id: 'exec_sim_wh_03',
      merchant_id: 'merch_acme_tech_01',
      incident_id: 'inc_webhook_lag_03',
      action_id: 'act_wh_03',
      provider: 'simulation_adapter',
      action_type: 'webhook_resync',
      status: 'simulated',
      is_simulated: true,
      provider_reference: 'sim_wh_resync_41a',
      idempotency_key: 'exec_act_wh_03_1725541000',
      executed_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      details: {
        mode: 'sandbox_simulation',
        target_pipe: 'webhook_delivery_fast_pipe',
        notice: 'Executed truthfully under sandbox simulation adapter.',
      },
    },
    outcome: {
      outcome_id: 'out_wh_03',
      incident_id: 'inc_webhook_lag_03',
      action_id: 'act_wh_03',
      outcome_type: 'revenue_protected',
      amount: '18000.00',
      currency: 'INR',
      status: 'verified',
      measured_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      reference_data: {
        merchant_id: 'merch_acme_tech_01',
        incident_id: 'inc_webhook_lag_03',
        action_id: 'act_wh_03',
        execution_id: 'exec_sim_wh_03',
        execution_status: 'simulated',
        execution_provider: 'simulation_adapter',
        is_simulated: true,
        verification_status: 'verified_success',
        revenue_at_risk: '18000.00',
        recovered_revenue: '0.00',
        protected_revenue: '18000.00',
        total_impact: '18000.00',
        recovery_rate: '1.0000',
        remaining_revenue_at_risk: '0.00',
        correlation_id: 'corr-webhook-03',
      },
    },
  },

  'inc_settlement_04': {
    incident: {
      incident_id: 'inc_settlement_04',
      merchant_id: 'merch_acme_tech_01',
      incident_type: 'settlement_delay',
      severity: 'low',
      status: 'detected',
      detected_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      revenue_at_risk: '8500.00',
      currency: 'INR',
      confidence: '0.82',
      description: 'Scheduled batch settlement payout delayed past standard T+1 window.',
    },
    evidences: [
      {
        evidence_id: 'ev_set_01',
        incident_id: 'inc_settlement_04',
        evidence_type: 'telemetry_metric',
        source: 'settlement_pipeline',
        observed_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
        summary: 'Bank holiday processing schedule mismatch for nodal account transfer.',
        metrics_data: { nodal_bank: 'YES_BANK', delay_hours: 4.5 },
      },
    ],
    investigation: {
      incident_id: 'inc_settlement_04',
      primary_cause: 'Clearing house holiday calendar offset caused automated batch payout queue deferral.',
      secondary_causes: [],
      confidence: 0.88,
      confidence_rationale: 'Nodal account reconciliation log confirms fund reservation without dispatch failure.',
      affected_cohorts: ['DAILY_SETTLEMENT_MERCHANTS'],
      evidence_keys_used: ['ev_set_01'],
      is_conclusive: true,
    },
    proposed_action: {
      action_id: 'act_set_04',
      incident_id: 'inc_settlement_04',
      action_type: 'merchant_alert',
      target: 'merchant_ops_notification_bus',
      expected_recovery: '8500.00',
      currency: 'INR',
      risk_level: 'low',
      confidence: '0.95',
      approval_required: false,
      status: 'approved',
      rationale: 'Broadcast verified settlement schedule delay notice and trigger expedited RTGS clearing batch.',
      created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    },
    policy_decision: {
      decision_id: 'pol_dec_04',
      action_id: 'act_set_04',
      incident_id: 'inc_settlement_04',
      merchant_id: 'merch_acme_tech_01',
      decision: 'allow',
      reasons: ['Informational merchant alert is on allowlist.', 'Amount ₹8,500.00 is well below ₹50,000 auto-cap.'],
      rule_results: [
        { rule_code: 'input_integrity', passed: true, decision_impact: 'allow', message: 'Valid input format.', evaluated_data: {} },
        { rule_code: 'action_allowlist', passed: true, decision_impact: 'allow', message: 'merchant_alert is permitted.', evaluated_data: {} },
        { rule_code: 'monetary_limit', passed: true, decision_impact: 'allow', message: 'Within auto-allow cap.', evaluated_data: {} },
      ],
      evaluated_limits: { policy_version: '1.0.0' },
      policy_version: '1.0.0',
      evaluated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    },
    execution_result: {
      execution_id: 'exec_sim_set_04',
      merchant_id: 'merch_acme_tech_01',
      incident_id: 'inc_settlement_04',
      action_id: 'act_set_04',
      provider: 'simulation_adapter',
      action_type: 'merchant_alert',
      status: 'simulated',
      is_simulated: true,
      provider_reference: 'sim_settle_alert_88c',
      idempotency_key: 'exec_act_set_04_1725542000',
      executed_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
      details: {
        mode: 'sandbox_simulation',
        target: 'merchant_ops_notification_bus',
        notice: 'Executed truthfully under sandbox simulation adapter.',
      },
    },
    outcome: {
      outcome_id: 'out_set_04',
      incident_id: 'inc_settlement_04',
      action_id: 'act_set_04',
      outcome_type: 'revenue_protected',
      amount: '8500.00',
      currency: 'INR',
      status: 'verified',
      measured_at: new Date().toISOString(),
      reference_data: {
        merchant_id: 'merch_acme_tech_01',
        incident_id: 'inc_settlement_04',
        action_id: 'act_set_04',
        execution_id: 'exec_sim_set_04',
        execution_status: 'simulated',
        execution_provider: 'simulation_adapter',
        is_simulated: true,
        verification_status: 'verified_success',
        revenue_at_risk: '8500.00',
        recovered_revenue: '0.00',
        protected_revenue: '8500.00',
        total_impact: '8500.00',
        recovery_rate: '1.0000',
        remaining_revenue_at_risk: '0.00',
        correlation_id: 'corr-settle-04',
      },
    },
  },
};
